"""Material grammar: compose treatments instead of storing them.

The first version of this file held ten finished treatment strings, so every
cyanotype scene in every video got the identical prompt and the look read as
a filter preset. Here a treatment is *composed* at plan time from a physical
family plus sampled modifiers, so two cyanotypes are two different objects —
different sheet, different exposure, different damage, different lighting.

Structure:
    family    a physically-real substrate+process pair (the part that must
              stay coherent — "cyanotype on rag paper", "intaglio etching")
    palette   a colour constraint the family actually admits
    emphasis  which physical quality to foreground (fibre, tooth, burr...)
    artifacts 1-3 process defects, the main source of felt uniqueness
    capture   how the object is lit and photographed
    wear      its age and condition

Sampling is seeded, so a manifest reproduces exactly. Per-shot jitter
re-rolls artifacts only, which makes each shot read as a separate physical
artefact rather than one image with a filter over it.

Rule that still governs everything: name the *physical process*. Abstract
optical asks ("formed from thin-film interference") collapse to photoreal.
"""
import random

FAMILIES = {
    "cyanotype": {
        "affinity": {"valence": 0.25, "energy": 0.2, "warmth": 0.15, "age": 0.75, "tactility": 0.35},
        "mood": "cold, still, elegiac, archival",
        "leads": [
            "Cyanotype sun print on {sub}:",
            "Hand-coated cyanotype contact print on {sub}:",
            "Blueprint-process sun exposure on {sub}:",
        ],
        "substrates": ["rough cotton rag paper", "heavy watercolour paper",
                       "thin unsized mulberry paper", "coarse linen cloth",
                       "buff-toned printmaking stock"],
        "core": "Prussian blue where the light struck and bare substrate where it did not, no true midtones",
        "palettes": ["deep Prussian blue and raw paper white only",
                     "faded slate-blue washed almost to grey",
                     "blue-black shadows with warm cream highlights",
                     "toned brown-violet from a tannin bath"],
        "emphasis": ["visible paper fibre in the highlights",
                     "the brush-stroked edge of the hand-coated emulsion",
                     "the deckle edge of the sheet",
                     "uneven coating leaving lighter streaks"],
        "artifacts": ["streaks where the emulsion was brushed unevenly",
                      "pale fingerprints at the sheet margin",
                      "a bleached halo where the sheet lifted during exposure",
                      "hard-edged contact shadows from the negative's tape",
                      "foxing spots blooming through the blue",
                      "a crease running through the print",
                      "uneven wash-out leaving a tidemark"],
        "captures": ["photographed flat under diffuse north light",
                     "scanned on a flatbed, dead flat and slightly over-lit",
                     "held up against a window, light coming through the sheet",
                     "lying on a table with the sheet curling at one corner"],
        "wear": ["freshly washed and still faintly damp", "decades old and sun-faded",
                 "handled often, soft at the corners", "archival and pristine"],
    },
    "etching": {
        "affinity": {"valence": 0.3, "energy": 0.3, "warmth": 0.35, "age": 0.9, "tactility": 0.45},
        "mood": "austere, antique, melancholy, precise",
        "leads": ["Copperplate etching, intaglio print on {sub}:",
                  "Hand-pulled intaglio etching on {sub}:",
                  "Drypoint and etching impression on {sub}:"],
        "substrates": ["off-white laid paper", "heavy cream printmaking paper",
                       "thin India paper", "toned tan stock"],
        "core": "the image built entirely from bitten lines and cross-hatching, ink sitting in the grooves",
        "palettes": ["warm sepia-black ink on off-white",
                     "cold blue-black ink", "sanguine red-brown ink",
                     "dense carbon black with grey plate tone"],
        "emphasis": ["the velvety burr of drypoint lines",
                     "the embossed plate mark pressed into the paper",
                     "dense cross-hatching modelling the shadows",
                     "open unworked paper carrying the highlights"],
        "artifacts": ["plate tone smeared unevenly across the background",
                      "a scratch running across the plate",
                      "over-bitten passages gone blotchy and dark",
                      "the plate edge printing as a dark rectangle",
                      "ink squeezed into a ridge at one margin",
                      "foul-biting speckle in the open areas"],
        "captures": ["photographed flat in raking light so the embossing shows",
                     "scanned flat and sharp", "lying under glass with a slight reflection"],
        "wear": ["a crisp early impression", "a late worn impression, lines going grey",
                 "foxed and yellowed with age"],
    },
    "felted": {
        "affinity": {"valence": 0.85, "energy": 0.35, "warmth": 0.95, "age": 0.3, "tactility": 0.95},
        "mood": "warm, tender, handmade, childlike",
        "leads": ["Needle-felted wool diorama, {cap}:",
                  "Handmade felted wool model, {cap}:",
                  "Wet-felted and needle-sculpted wool scene, {cap}:"],
        "substrates": ["dyed carded wool", "undyed natural fleece with dyed accents",
                       "wool over a wire armature", "mixed wool and silk fibre"],
        "core": "every surface built from matted wool fibre, soft and slightly fuzzy, sitting on a tabletop",
        "palettes": ["heathered naturals with one saturated accent colour",
                     "soft dusty pastels", "deep saturated dyed jewel tones",
                     "undyed creams and greys"],
        "emphasis": ["loose fibre wisps catching the light",
                     "visible needle-poke pockmarks over every surface",
                     "the fuzzy halo at every silhouette edge",
                     "compacted denser felt where the piece was worked hardest"],
        "artifacts": ["a felting needle left stuck in the piece",
                      "loose fibres scattered on the table around it",
                      "a seam where two felted parts were joined",
                      "the wire armature showing through at one point",
                      "slight sagging where the felt is under-worked",
                      "stray coloured fibres migrated into the wrong area"],
        "captures": ["photographed in soft daylight with shallow depth of field",
                     "lit from one side with a warm lamp, long soft shadows",
                     "overhead flat-lay on a plain linen cloth",
                     "macro close focus, the background falling away"],
        "wear": ["freshly made, fibres still crisp", "pilled and dusty from handling",
                 "slightly compressed as if stored in a box"],
    },
    "risograph": {
        "affinity": {"valence": 0.8, "energy": 0.8, "warmth": 0.6, "age": 0.2, "tactility": 0.3},
        "mood": "bright, punchy, graphic, youthful",
        "leads": ["Risograph print, {pal}, on {sub}:",
                  "Two-colour riso duplicator print on {sub}:",
                  "Mimeograph-style stencil duplicator print on {sub}:"],
        "substrates": ["matte uncoated newsprint", "cheap grey pulp paper",
                       "bright white copy stock", "recycled speckled stock"],
        "core": "flat poster shapes built from overlapping ink layers, no continuous tone",
        "palettes": ["fluorescent pink and teal", "federal blue and warm red",
                     "bright yellow and black", "green and fluorescent orange"],
        "emphasis": ["visible halftone dot screens in the mid-tones",
                     "the moiré where two dot screens overlap",
                     "flat blocks of unbroken ink",
                     "the paper showing through the thin ink"],
        "artifacts": ["misregistration offsetting one ink layer by a few millimetres",
                      "roller streaks running down the sheet",
                      "ink smudged by handling at one corner",
                      "a paper-feed crease across the print",
                      "patchy coverage where the drum ran dry",
                      "show-through from the reverse side"],
        "captures": ["scanned flat", "photographed on a desk under flat light",
                     "pinned to a wall, edges curling"],
        "wear": ["fresh off the drum, ink still offsetting",
                 "sun-bleached, the fluorescent gone pale", "creased from being folded"],
    },
    "collodion": {
        "affinity": {"valence": 0.15, "energy": 0.25, "warmth": 0.3, "age": 0.95, "tactility": 0.4},
        "mood": "haunted, historical, decayed, solemn",
        "leads": ["Wet-plate collodion tintype, {cap}:",
                  "Ambrotype on glass, {cap}:",
                  "Wet-collodion negative printed as a positive, {cap}:"],
        "substrates": ["blackened iron plate", "clear glass plate",
                       "aluminium trophy plate"],
        "core": "shallow tonal range with silver highlights and deep empty shadows, extremely shallow focus",
        "palettes": ["warm neutral grey with tarnished silver highlights",
                     "cold blue-grey", "sepia-toned brown-black",
                     "silver going iridescent where it has tarnished"],
        "emphasis": ["the sweep of collodion pour visible across the plate",
                     "the fall-off into total black at the edges",
                     "silver highlights that read almost metallic",
                     "one plane of razor focus and everything else dissolving"],
        "artifacts": ["comet-tail streaks from dust in the pour",
                      "bromide drips running from the plate edge",
                      "the collodion lifting and flaking at one corner",
                      "chemical staining blooming across one side",
                      "fingerprints of the plate holder at the margins",
                      "a scratch through the emulsion"],
        "captures": ["photographed on black velvet", "held in a hand at an angle so the silver flares",
                     "scanned flat against black"],
        "wear": ["freshly varnished and glossy", "flaking and half-lost",
                 "the varnish yellowed and crazed"],
    },
    "cutpaper": {
        "affinity": {"valence": 0.65, "energy": 0.3, "warmth": 0.6, "age": 0.35, "tactility": 0.85},
        "mood": "delicate, storybook, quiet, constructed",
        "leads": ["Layered cut-paper diorama in a shadow box, {cap}:",
                  "Hand-cut paper theatre with stacked planes, {cap}:",
                  "Papercut scene built in receding layers, {cap}:"],
        "substrates": ["textured coloured cardstock", "heavy watercolour paper",
                       "thin tracing paper and cardstock mixed", "corrugated board and tissue"],
        "core": "the scene built from separate stacked planes of cut paper with real air between them",
        "palettes": ["a narrow range of blues and greys deepening with distance",
                     "warm creams and ochres", "high-contrast black and white with one red",
                     "soft faded pastels"],
        "emphasis": ["the cut edge of every layer catching the light",
                     "drop shadows falling from each plane onto the next",
                     "the paper's tooth visible across the flat areas",
                     "translucent tissue glowing where light passes through"],
        "artifacts": ["a slightly ragged cut where the blade slipped",
                      "visible glue tabs holding a layer",
                      "one layer buckling away from flat",
                      "a pencil guideline left uncut",
                      "dust settled in the gaps between layers"],
        "captures": ["lit from one side to throw the layer shadows long",
                     "backlit so the tissue layers glow",
                     "photographed straight on in flat museum light"],
        "wear": ["crisply new", "sun-faded on one side", "dented from storage"],
    },
    "stainedglass": {
        "affinity": {"valence": 0.75, "energy": 0.6, "warmth": 0.55, "age": 0.85, "tactility": 0.7},
        "mood": "transcendent, devotional, radiant",
        "leads": ["Stained glass panel, {cap}:",
                  "Leaded glass window, {cap}:",
                  "Painted and fired glass panel in lead came, {cap}:"],
        "substrates": ["hand-blown cathedral glass", "opalescent glass",
                       "streaky antique glass", "thick slab glass set in concrete"],
        "core": "saturated coloured glass divided by heavy dark lead lines, lit from behind",
        "palettes": ["deep cobalt and ruby with gold", "cool greens and blue-greys",
                     "amber and bottle green", "predominantly white and silver-stain yellow"],
        "emphasis": ["bubbles and striations trapped in the hand-blown glass",
                     "the black lead came drawing every contour",
                     "painted grisaille shading fired onto the glass",
                     "colour spilling onto the surrounding stone"],
        "artifacts": ["a cracked pane held by a repair lead",
                      "one pane replaced in a mismatched colour",
                      "dirt and grime built up in the lower corners",
                      "the lead sagging and bowing with age",
                      "condensation blurring part of the panel"],
        "captures": ["backlit by grey daylight", "backlit by low warm sun, colour thrown across the frame",
                     "photographed at an angle so the glass surface reflects"],
        "wear": ["newly leaded and bright", "centuries old, buckled and grimy",
                 "partly restored, some panes clean and some dark"],
    },
    "verdigris": {
        "affinity": {"valence": 0.25, "energy": 0.55, "warmth": 0.35, "age": 0.9, "tactility": 0.9},
        "mood": "ancient, corroded, heavy, elemental",
        "leads": ["Oxidised copper relief panel, {cap}:",
                  "Hammered bronze plaque with patina, {cap}:",
                  "Repoussé copper sheet, corroded, {cap}:"],
        "substrates": ["hammered copper sheet", "cast bronze", "beaten brass plate"],
        "core": "raised metal forms worked in relief, the surface eaten by patina",
        "palettes": ["deep verdigris green over raw copper",
                     "blue-green patina with black recesses",
                     "brown-black bronze with green only in the hollows",
                     "bright polished metal against corroded areas"],
        "emphasis": ["hammer facets across the flat areas",
                     "mineral crust built up thick in the recesses",
                     "corrosion pitting eating into the raised forms",
                     "polished high points where hands have rubbed it"],
        "artifacts": ["a repair patch soldered across one area",
                      "drips of green running down from the recesses",
                      "a dent distorting the relief",
                      "rivet heads punching through the design",
                      "salt bloom crusting one edge"],
        "captures": ["in hard raking light so the relief throws shadows",
                     "under flat overcast light", "lit from below, shadows running upward"],
        "wear": ["freshly patinated", "centuries buried and only just cleaned",
                 "weathered outdoors for decades"],
    },
    "ukiyoe": {
        "affinity": {"valence": 0.6, "energy": 0.45, "warmth": 0.55, "age": 0.8, "tactility": 0.35},
        "mood": "stylized, flowing, poised",
        "leads": ["Japanese woodblock ukiyo-e print on {sub}:",
                  "Multi-block nishiki-e colour woodcut on {sub}:",
                  "Hand-printed woodblock impression on {sub}:"],
        "substrates": ["aged mulberry washi paper", "thin kozo paper",
                       "cream hosho paper"],
        "core": "flat carved colour planes bounded by a printed keyline, no shading",
        "palettes": ["indigo and safflower red with black keyline",
                     "muted mineral greens and ochres",
                     "predominantly indigo blues (aizuri-e)",
                     "faded pinks and greys, the fugitive pigments gone"],
        "emphasis": ["woodgrain printing through the flat colour areas",
                     "the bokashi gradient hand-wiped on the block",
                     "the embossed impression of the block in the paper",
                     "the crisp carved keyline"],
        "artifacts": ["one colour block slightly out of register",
                      "a wormhole through the sheet",
                      "the paper browned and brittle at the edges",
                      "an ink-heavy pull with the colour gone muddy",
                      "a horizontal fold from being bound in an album"],
        "captures": ["photographed flat in even light", "scanned flat",
                     "lit at a low angle so the paper texture and embossing read"],
        "wear": ["a fresh early impression", "faded by two centuries of light",
                 "water-stained along one edge"],
    },
    "raku": {
        "affinity": {"valence": 0.45, "energy": 0.7, "warmth": 0.7, "age": 0.6, "tactility": 0.9},
        "mood": "volatile, lustrous, earthy",
        "leads": ["Raku-fired ceramic surface, {cap}:",
                  "Glazed and reduction-fired stoneware, {cap}:",
                  "Pit-fired earthenware with lustre glaze, {cap}:"],
        "substrates": ["grogged stoneware clay", "smooth white earthenware",
                       "dark iron-rich clay body"],
        "core": "a thick glaze crazed into a fine crackle over a scorched clay body",
        "palettes": ["copper lustre iridescence over black",
                     "white crackle glaze with carbon-blackened crazing",
                     "turquoise glaze breaking to bronze at the edges",
                     "unglazed smoke-blackened clay with one glazed passage"],
        "emphasis": ["the crackle network filled with carbon",
                     "glaze pooling thick in the hollows and thin on the ridges",
                     "flashing where the flame licked the piece",
                     "raw grogged clay contrasting with glassy glaze"],
        "artifacts": ["a firing crack running through the piece",
                      "a bare patch where the glaze crawled",
                      "kiln shelf scars on the underside",
                      "pinholes bubbled through the glaze",
                      "an ash deposit fused to one side"],
        "captures": ["lit hard so the lustre flares", "in soft light showing the crackle",
                     "macro close on the glaze surface"],
        "wear": ["straight from the reduction bin", "handled for years, lustre worn thin",
                 "chipped at the rim"],
    },
}

# Cross-family palette-ish global look, sampled per video so different videos
# of the same family still differ.
GLOBAL_GRADE = [
    "the whole image slightly cool", "the whole image slightly warm",
    "low contrast and dusty", "high contrast and clean",
    "a touch overexposed", "a touch dark and dense",
]

BY_LEVEL = {
    "low": ["cyanotype", "collodion", "etching", "cutpaper", "ukiyoe"],
    "mid": ["etching", "ukiyoe", "verdigris", "cutpaper", "raku"],
    "high": ["felted", "risograph", "stainedglass", "raku", "verdigris"],
}

MATERIALS = FAMILIES  # back-compat for specs that reference family keys


def compose(family_key: str, seed: int, n_artifacts: int = 2) -> dict:
    """Sample one concrete treatment from a family.

    Same key + same seed always yields the same treatment, so a manifest
    reproduces. Different seeds yield materially different objects rather
    than the same string every time.
    """
    fam = FAMILIES[family_key]
    rng = random.Random(seed)

    sub = rng.choice(fam["substrates"])
    cap = rng.choice(fam["captures"])
    pal = rng.choice(fam["palettes"])
    lead = rng.choice(fam["leads"]).format(sub=sub, cap=cap, pal=pal)

    picks = rng.sample(fam["artifacts"], min(n_artifacts, len(fam["artifacts"])))
    style = ". ".join([
        fam["core"].capitalize(),
        f"Colour: {pal}",
        f"Surface: {rng.choice(fam['emphasis'])}",
        f"Condition: {rng.choice(fam['wear'])}",
        f"Flaws: {'; '.join(picks)}",
        rng.choice(GLOBAL_GRADE).capitalize(),
        "No photorealism — the material and the process that made it are the subject",
    ]) + "."
    return {"lead": lead, "style": style, "family": family_key,
            "substrate": sub, "palette": pal, "artifacts": picks}


def jitter(family_key: str, base_seed: int, shot_seed: int) -> dict:
    """Per-shot variation: same object family and palette, fresh flaws.

    Keeps a scene coherent while making each shot read as its own physical
    artefact — a different sheet, a different pull — instead of one image
    with a filter over it.
    """
    base = compose(family_key, base_seed)
    rng = random.Random(shot_seed)
    fam = FAMILIES[family_key]
    picks = rng.sample(fam["artifacts"], min(2, len(fam["artifacts"])))
    style = base["style"].replace(
        f"Flaws: {'; '.join(base['artifacts'])}", f"Flaws: {'; '.join(picks)}")
    return {"lead": base["lead"], "style": style, "family": family_key}


# Second tranche — widens the grammar so vibe matching has real range to
# choose from rather than ten options. Same structure; affinity axes are
# valence (bleak..joyful), energy (still..frantic), warmth (cold..warm),
# age (contemporary..antique), tactility (flat..dimensional).
FAMILIES.update({
    "lithograph": {
        "affinity": {"valence": 0.4, "energy": 0.35, "warmth": 0.4, "age": 0.8, "tactility": 0.3},
        "mood": "smoky, tonal, brooding, literary",
        "leads": ["Stone lithograph printed on {sub}:", "Hand-drawn litho crayon print on {sub}:",
                  "Tusche-wash lithograph on {sub}:"],
        "substrates": ["heavy cream printmaking paper", "soft grey wove paper",
                       "thin cover stock", "buff-toned rag paper"],
        "core": "continuous greasy tone drawn with litho crayon, grain of the stone carried into every mark",
        "palettes": ["dense black on cream", "warm bistre brown", "two stones, black over pale ochre",
                     "cold grey-black with a blue undertone"],
        "emphasis": ["the granular tooth of the stone in every mid-tone",
                     "wash passages pooling into mottled tone",
                     "crayon strokes still legible in the darks",
                     "bright untouched paper carrying the highlights"],
        "artifacts": ["scumming greying the open areas", "a roller mark across the sheet",
                      "the stone's edge printing faintly", "one passage filled in too dark",
                      "a thumbprint in the margin"],
        "captures": ["photographed flat under soft light", "scanned flat",
                     "raking light showing the paper tooth"],
        "wear": ["a crisp early pull", "yellowed and foxed", "rubbed and smudged at the edges"],
    },
    "silkscreen": {
        "affinity": {"valence": 0.75, "energy": 0.75, "warmth": 0.5, "age": 0.3, "tactility": 0.4},
        "mood": "bold, flat, pop, insistent",
        "leads": ["Hand-pulled silkscreen print on {sub}:", "Serigraph, {pal}, on {sub}:",
                  "Screen print with heavy ink deposit on {sub}:"],
        "substrates": ["heavy poster stock", "coarse chipboard", "bright white card",
                       "brown kraft paper"],
        "core": "flat opaque ink laid in separate screens, hard-edged shapes with no gradation",
        "palettes": ["three flat colours plus black", "day-glo orange and deep blue",
                     "monochrome black on coloured stock", "muted olive, rust and bone"],
        "emphasis": ["the thick raised ink you can feel", "the weave of the mesh in the flat areas",
                     "hard knife-cut stencil edges", "one screen slightly translucent over another"],
        "artifacts": ["a pinhole letting ink through where it shouldn't",
                      "the squeegee starting mark at one edge", "registration off by a hair",
                      "ink drying patchy in a large flat", "fibres stuck in the wet ink"],
        "captures": ["photographed flat, hard even light", "at an angle so the ink relief catches light",
                     "taped to a studio wall"],
        "wear": ["fresh and glossy", "sun-bleached in the fluorescents", "creased and thumbed"],
    },
    "embroidery": {
        "affinity": {"valence": 0.7, "energy": 0.3, "warmth": 0.85, "age": 0.6, "tactility": 0.9},
        "mood": "patient, domestic, intimate, devotional",
        "leads": ["Hand-embroidered panel on {sub}:", "Silk thread embroidery worked on {sub}:",
                  "Crewelwork in wool on {sub}:"],
        "substrates": ["coarse natural linen", "even-weave cotton", "loosely woven hessian",
                       "fine bleached lawn"],
        "core": "the image worked entirely in stitches, thread direction shaping every form",
        "palettes": ["muted vegetable-dyed wools", "bright silks against undyed ground",
                     "a single dark thread on pale cloth", "faded pinks, sage and bone"],
        "emphasis": ["the sheen of silk floss catching light along the stitch direction",
                     "the woven grid of the ground cloth showing between stitches",
                     "raised satin stitch standing proud of the surface",
                     "long-and-short shading blending one colour into the next"],
        "artifacts": ["loose thread ends left hanging on the reverse showing through",
                      "the hoop's ring pressed into the cloth", "one area unfinished, ground cloth bare",
                      "a knot pulling the weave tight", "colours faded unevenly by light"],
        "captures": ["raking light so the stitches throw shadows", "macro close on the thread",
                     "flat-lit and pinned taut"],
        "wear": ["newly finished, thread still bright", "an heirloom, faded and softened",
                 "moth-nibbled at one corner"],
    },
    "fresco": {
        "affinity": {"valence": 0.5, "energy": 0.3, "warmth": 0.7, "age": 0.95, "tactility": 0.75},
        "mood": "monumental, sun-bleached, ruined, sacred",
        "leads": ["Buon fresco on {sub}:", "Wall painting in lime plaster on {sub}:",
                  "Fragment of a fresco cycle on {sub}:"],
        "substrates": ["lime plaster over rough masonry", "thin intonaco over brick",
                       "plaster laid on a curved vault"],
        "core": "pigment sunk into damp lime plaster, matte and chalky, part of the wall itself",
        "palettes": ["earth reds, ochres and lime white", "faded azurite blue and terre verte",
                     "sun-bleached to pale pinks and buffs", "charcoal underdrawing showing through"],
        "emphasis": ["giornata joins where a day's plaster meets the next",
                     "the chalky matte surface refusing to shine",
                     "incised guidelines cut into the wet plaster",
                     "the rough aggregate of the plaster showing through thin passages"],
        "artifacts": ["large losses where the plaster has fallen away",
                      "a crack running through the composition", "salt efflorescence blooming white",
                      "smoke blackening across one corner", "later graffiti scratched into the surface"],
        "captures": ["lit by raking daylight from a high window", "flat archaeological documentation lighting",
                     "photographed at an angle showing the wall's curve"],
        "wear": ["recently uncovered and cleaned", "centuries of soot and loss",
                 "partly restored, losses filled flat"],
    },
    "linocut": {
        "affinity": {"valence": 0.55, "energy": 0.65, "warmth": 0.45, "age": 0.5, "tactility": 0.45},
        "mood": "blunt, vigorous, graphic, worked",
        "leads": ["Linocut relief print on {sub}:", "Hand-burnished lino block print on {sub}:",
                  "Reduction linocut on {sub}:"],
        "substrates": ["thin Japanese printing paper", "heavy cartridge paper",
                       "newsprint", "tinted sugar paper"],
        "core": "bold cut shapes with visible gouge marks, ink sitting flat on the raised surface",
        "palettes": ["black ink only", "black over one flat colour",
                     "three reduction layers, dark to light", "red and black on cream"],
        "emphasis": ["the chatter of the gouge across cleared areas",
                     "chunky uncut blacks against fine cut lines",
                     "ink slightly heavier at the block edges",
                     "the paper's texture breaking the flat ink"],
        "artifacts": ["clearing marks printing as faint grey texture",
                      "the block edge printing as a hard border", "an under-inked patch going pale",
                      "a slip of the gouge cutting into a form", "burnishing marks on the reverse showing"],
        "captures": ["photographed flat", "held up, paper slightly rippled", "scanned flat"],
        "wear": ["a clean fresh pull", "a late pull, block worn", "creased from storage"],
    },
    "daguerreotype": {
        "affinity": {"valence": 0.2, "energy": 0.15, "warmth": 0.25, "age": 1.0, "tactility": 0.5},
        "mood": "spectral, mirror-like, uncanny, funereal",
        "leads": ["Daguerreotype on {sub}:", "Mirror-polished daguerreotype plate, {cap}:",
                  "Sixth-plate daguerreotype, {cap}:"],
        "substrates": ["silver-plated copper", "highly polished silvered plate"],
        "core": "a mirror surface holding a faint image that flips positive to negative as the angle shifts",
        "palettes": ["silver-white and shadow with no true black", "warm gilt-toned silver",
                     "cold steel grey", "hand-tinted pink on the cheeks only"],
        "emphasis": ["the mirror ground reflecting whatever is in front of it",
                     "buffing scratches circling the plate",
                     "impossibly fine detail in the highlights",
                     "the image dissolving to nothing at certain angles"],
        "artifacts": ["tarnish blooming in rainbow rings from the edges",
                      "the brass mat's impression around the image", "a wipe mark across the plate",
                      "dust motes fused to the silver", "black spotting eating into the image"],
        "captures": ["photographed against black so the image reads positive",
                     "tilted so half the plate flares to mirror", "under glass in its case"],
        "wear": ["freshly sealed and brilliant", "heavily tarnished", "cracked cover glass over it"],
    },
    "mosaic": {
        "affinity": {"valence": 0.65, "energy": 0.5, "warmth": 0.6, "age": 0.9, "tactility": 0.85},
        "mood": "eternal, fragmented, ceremonial, patient",
        "leads": ["Tessellated mosaic in {sub}:", "Byzantine-style mosaic worked in {sub}:",
                  "Floor mosaic laid in {sub}:"],
        "substrates": ["gold-leaf glass smalti", "cut stone and marble tesserae",
                       "terracotta and limestone cubes", "mixed glass and shell"],
        "core": "the image assembled from thousands of small hard tesserae with visible mortar between them",
        "palettes": ["gold ground with deep blues and reds", "muted stone naturals",
                     "black and white geometric only", "sea greens and bone"],
        "emphasis": ["each tessera set at a slightly different angle, catching light unevenly",
                     "the andamento, rows of tesserae flowing around the forms",
                     "grout lines drawing a grid across everything",
                     "gold tesserae flaring where the light hits"],
        "artifacts": ["a section lost, bare mortar bed showing", "later repairs in mismatched stone",
                      "the floor buckled by subsidence", "lime crust over one area",
                      "a crack running through, tesserae displaced"],
        "captures": ["lit obliquely so every tessera casts a shadow",
                     "photographed from directly above", "under a shaft of daylight"],
        "wear": ["newly laid and sharp", "worn smooth by centuries of feet", "excavated and partly cleaned"],
    },
    "chemigram": {
        "affinity": {"valence": 0.35, "energy": 0.85, "warmth": 0.4, "age": 0.4, "tactility": 0.6},
        "mood": "chaotic, alchemical, corroded, feverish",
        "leads": ["Chemigram on {sub}:", "Darkroom chemigram, developer and fixer painted onto {sub}:",
                  "Cameraless chemical painting on {sub}:"],
        "substrates": ["fibre-based silver gelatin paper", "expired resin-coated paper",
                       "large-format sheet film"],
        "core": "form emerging from chemistry eating into the emulsion, not from a lens",
        "palettes": ["silver-black bleeding into cream", "sepia and bruised violet",
                     "cold blue-black with bleached voids", "toned brown with metallic sheen"],
        "emphasis": ["tide lines where the chemistry crept",
                     "solarised edges reversing tone", "crystalline blooms in the emulsion",
                     "the resist's mark where it held the developer off"],
        "artifacts": ["drips running against the composition", "the emulsion lifting and wrinkling",
                      "fingerprints developed into the image", "a bleached hole burnt through",
                      "spatter across one corner"],
        "captures": ["scanned flat", "photographed wet and glistening", "pinned up, curling"],
        "wear": ["still wet from the tray", "dried and cockled", "silvered out with age"],
    },
    "batik": {
        "affinity": {"valence": 0.7, "energy": 0.45, "warmth": 0.8, "age": 0.65, "tactility": 0.7},
        "mood": "sinuous, ceremonial, saturated, flowing",
        "leads": ["Wax-resist batik on {sub}:", "Hand-drawn tulis batik on {sub}:",
                  "Multiple-dip batik dyed on {sub}:"],
        "substrates": ["fine cotton cloth", "heavy silk", "coarse handwoven cotton"],
        "core": "colour laid by repeated dyeing, wax holding back each area, cloth weave throughout",
        "palettes": ["indigo and soga brown on cream", "deep rust, indigo and black",
                     "single indigo dip, pale to saturated", "turmeric yellow and madder red"],
        "emphasis": ["the crackle where wax broke and dye seeped into the veins",
                     "the canting's hand-drawn line wavering slightly",
                     "the cloth's weave visible through the dye",
                     "colour bleeding softly at every boundary"],
        "artifacts": ["wax residue leaving a stiff patch", "a dye run down one edge",
                      "uneven dyeing leaving cloudy bands", "a repair stitched across a tear",
                      "the selvedge fraying"],
        "captures": ["hung so the cloth falls in soft folds", "pinned flat, backlit faintly",
                     "photographed flat in even daylight"],
        "wear": ["newly dyed and vivid", "washed many times and softened",
                 "sun-faded along one fold"],
    },
    "charcoal": {
        "affinity": {"valence": 0.3, "energy": 0.55, "warmth": 0.45, "age": 0.55, "tactility": 0.5},
        "mood": "urgent, smudged, unresolved, breathing",
        "leads": ["Charcoal and white chalk drawing on {sub}:", "Vine charcoal study on {sub}:",
                  "Compressed charcoal drawing, heavily reworked, on {sub}:"],
        "substrates": ["grey-toned laid paper", "buff sugar paper", "rough grey card",
                       "warm-toned pastel paper"],
        "core": "the image built in smudged charcoal with the toned paper carrying the mid-tone",
        "palettes": ["charcoal black and white chalk on grey",
                     "black only, paper doing the rest", "black and sanguine on buff",
                     "soft greys with one dense black accent"],
        "emphasis": ["fingerprints where the charcoal was blended by hand",
                     "the paper's tooth grabbing the charcoal",
                     "erased passages ghosting under the surface",
                     "white chalk sitting chalky and opaque on top"],
        "artifacts": ["smudges dragged outside the forms", "a pentimento of an earlier position showing",
                      "fixative spray mottling one area", "the sheet's fold running through",
                      "loose charcoal dust caught in the tooth"],
        "captures": ["raking light showing the paper tooth", "photographed flat and even",
                     "pinned to a board, corners curling"],
        "wear": ["fresh and unfixed, still dusty", "rubbed and blurred from handling",
                 "yellowed, the chalk gone dull"],
    },
})

BY_LEVEL = {
    "low": ["cyanotype", "collodion", "etching", "cutpaper", "ukiyoe",
            "lithograph", "daguerreotype", "charcoal"],
    "mid": ["etching", "ukiyoe", "verdigris", "cutpaper", "raku",
            "lithograph", "embroidery", "linocut", "mosaic", "batik", "fresco"],
    "high": ["felted", "risograph", "stainedglass", "raku", "verdigris",
             "silkscreen", "chemigram", "linocut"],
}
