"""Material grammar: compose treatments instead of storing them.

The first version of this file held ten finished treatment strings, so every
cyanotype scene in every video got the identical prompt and the look read as
a filter preset. Here a treatment is *composed* at plan time from a physical
family plus sampled modifiers, so two cyanotypes are two different objects —
different sheet, different exposure, different damage, different lighting.

Structure:
    family    a physically-real substrate+process pair (the part that must
              stay coherent — "cyanotype on rag paper", "intaglio etching")
    palette   a colour constraint the family actually admits
    emphasis  which physical quality to foreground (fibre, tooth, burr...)
    artifacts 1-3 process defects, the main source of felt uniqueness
    capture   how the object is lit and photographed
    wear      its age and condition

Sampling is seeded, so a manifest reproduces exactly. Per-shot jitter
re-rolls artifacts only, which makes each shot read as a separate physical
artefact rather than one image with a filter over it.

Rule that still governs everything: name the *physical process*. Abstract
optical asks ("formed from thin-film interference") collapse to photoreal.
"""
import random

FAMILIES = {
    "cyanotype": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.25, "energy": 0.2, "warmth": 0.15, "age": 0.75, "tactility": 0.35, "scale": 0.45, "organic": 0.2},
        "mood": "cold, still, elegiac, archival",
        "leads": [
            "Cyanotype sun print on {sub}:",
            "Hand-coated cyanotype contact print on {sub}:",
            "Blueprint-process sun exposure on {sub}:",
        ],
        "substrates": ["rough cotton rag paper", "heavy watercolour paper",
                       "thin unsized mulberry paper", "coarse linen cloth",
                       "buff-toned printmaking stock"],
        "core": "Prussian blue where the light struck and bare substrate where it did not, no true midtones",
        "palettes": ["deep Prussian blue and raw paper white only",
                     "faded slate-blue washed almost to grey",
                     "blue-black shadows with warm cream highlights",
                     "toned brown-violet from a tannin bath"],
        "emphasis": ["visible paper fibre in the highlights",
                     "the brush-stroked edge of the hand-coated emulsion",
                     "the deckle edge of the sheet",
                     "uneven coating leaving lighter streaks"],
        "artifacts": ["streaks where the emulsion was brushed unevenly",
                      "pale fingerprints at the sheet margin",
                      "a bleached halo where the sheet lifted during exposure",
                      "hard-edged contact shadows from the negative's tape",
                      "foxing spots blooming through the blue",
                      "a crease running through the print",
                      "uneven wash-out leaving a tidemark"],
        "captures": ["photographed flat under diffuse north light",
                     "scanned on a flatbed, dead flat and slightly over-lit",
                     "held up against a window, light coming through the sheet",
                     "lying on a table with the sheet curling at one corner"],
        "wear": ["freshly washed and still faintly damp", "decades old and sun-faded",
                 "handled often, soft at the corners", "archival and pristine"],
    },
    "etching": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.3, "energy": 0.3, "warmth": 0.35, "age": 0.9, "tactility": 0.45, "scale": 0.35, "organic": 0.2},
        "mood": "austere, antique, melancholy, precise",
        "leads": ["Copperplate etching, intaglio print on {sub}:",
                  "Hand-pulled intaglio etching on {sub}:",
                  "Drypoint and etching impression on {sub}:"],
        "substrates": ["off-white laid paper", "heavy cream printmaking paper",
                       "thin India paper", "toned tan stock"],
        "core": "the image built entirely from bitten lines and cross-hatching, ink sitting in the grooves",
        "palettes": ["warm sepia-black ink on off-white",
                     "cold blue-black ink", "sanguine red-brown ink",
                     "dense carbon black with grey plate tone"],
        "emphasis": ["the velvety burr of drypoint lines",
                     "the embossed plate mark pressed into the paper",
                     "dense cross-hatching modelling the shadows",
                     "open unworked paper carrying the highlights"],
        "artifacts": ["plate tone smeared unevenly across the background",
                      "a scratch running across the plate",
                      "over-bitten passages gone blotchy and dark",
                      "the plate edge printing as a dark rectangle",
                      "ink squeezed into a ridge at one margin",
                      "foul-biting speckle in the open areas"],
        "captures": ["photographed flat in raking light so the embossing shows",
                     "scanned flat and sharp", "lying under glass with a slight reflection"],
        "wear": ["a crisp early impression", "a late worn impression, lines going grey",
                 "foxed and yellowed with age"],
    },
    "felted": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.85, "energy": 0.35, "warmth": 0.95, "age": 0.3, "tactility": 0.95, "scale": 0.2, "organic": 0.45},
        "mood": "warm, tender, handmade, childlike",
        "leads": ["Needle-felted wool diorama, {cap}:",
                  "Handmade felted wool model, {cap}:",
                  "Wet-felted and needle-sculpted wool scene, {cap}:"],
        "substrates": ["dyed carded wool", "undyed natural fleece with dyed accents",
                       "wool over a wire armature", "mixed wool and silk fibre"],
        "core": "every surface built from matted wool fibre, soft and slightly fuzzy, sitting on a tabletop",
        "palettes": ["heathered naturals with one saturated accent colour",
                     "soft dusty pastels", "deep saturated dyed jewel tones",
                     "undyed creams and greys"],
        "emphasis": ["loose fibre wisps catching the light",
                     "visible needle-poke pockmarks over every surface",
                     "the fuzzy halo at every silhouette edge",
                     "compacted denser felt where the piece was worked hardest"],
        "artifacts": ["a felting needle left stuck in the piece",
                      "loose fibres scattered on the table around it",
                      "a seam where two felted parts were joined",
                      "the wire armature showing through at one point",
                      "slight sagging where the felt is under-worked",
                      "stray coloured fibres migrated into the wrong area"],
        "captures": ["photographed in soft daylight with shallow depth of field",
                     "lit from one side with a warm lamp, long soft shadows",
                     "overhead flat-lay on a plain linen cloth",
                     "macro close focus, the background falling away"],
        "wear": ["freshly made, fibres still crisp", "pilled and dusty from handling",
                 "slightly compressed as if stored in a box"],
    },
    "risograph": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.8, "energy": 0.8, "warmth": 0.6, "age": 0.2, "tactility": 0.3, "scale": 0.25, "organic": 0.1},
        "mood": "bright, punchy, graphic, youthful",
        "leads": ["Risograph print, {pal}, on {sub}:",
                  "Two-colour riso duplicator print on {sub}:",
                  "Mimeograph-style stencil duplicator print on {sub}:"],
        "substrates": ["matte uncoated newsprint", "cheap grey pulp paper",
                       "bright white copy stock", "recycled speckled stock"],
        "core": "flat poster shapes built from overlapping ink layers, no continuous tone",
        "palettes": ["fluorescent pink and teal", "federal blue and warm red",
                     "bright yellow and black", "green and fluorescent orange"],
        "emphasis": ["visible halftone dot screens in the mid-tones",
                     "the moiré where two dot screens overlap",
                     "flat blocks of unbroken ink",
                     "the paper showing through the thin ink"],
        "artifacts": ["misregistration offsetting one ink layer by a few millimetres",
                      "roller streaks running down the sheet",
                      "ink smudged by handling at one corner",
                      "a paper-feed crease across the print",
                      "patchy coverage where the drum ran dry",
                      "show-through from the reverse side"],
        "captures": ["scanned flat", "photographed on a desk under flat light",
                     "pinned to a wall, edges curling"],
        "wear": ["fresh off the drum, ink still offsetting",
                 "sun-bleached, the fluorescent gone pale", "creased from being folded"],
    },
    "collodion": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.15, "energy": 0.25, "warmth": 0.3, "age": 0.95, "tactility": 0.4, "scale": 0.3, "organic": 0.2},
        "mood": "haunted, historical, decayed, solemn",
        "leads": ["Wet-plate collodion tintype, {cap}:",
                  "Ambrotype on glass, {cap}:",
                  "Wet-collodion negative printed as a positive, {cap}:"],
        "substrates": ["blackened iron plate", "clear glass plate",
                       "aluminium trophy plate"],
        "core": "shallow tonal range with silver highlights and deep empty shadows, extremely shallow focus",
        "palettes": ["warm neutral grey with tarnished silver highlights",
                     "cold blue-grey", "sepia-toned brown-black",
                     "silver going iridescent where it has tarnished"],
        "emphasis": ["the sweep of collodion pour visible across the plate",
                     "the fall-off into total black at the edges",
                     "silver highlights that read almost metallic",
                     "one plane of razor focus and everything else dissolving"],
        "artifacts": ["comet-tail streaks from dust in the pour",
                      "bromide drips running from the plate edge",
                      "the collodion lifting and flaking at one corner",
                      "chemical staining blooming across one side",
                      "fingerprints of the plate holder at the margins",
                      "a scratch through the emulsion"],
        "captures": ["photographed on black velvet", "held in a hand at an angle so the silver flares",
                     "scanned flat against black"],
        "wear": ["freshly varnished and glossy", "flaking and half-lost",
                 "the varnish yellowed and crazed"],
    },
    "cutpaper": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.65, "energy": 0.3, "warmth": 0.6, "age": 0.35, "tactility": 0.85, "scale": 0.3, "organic": 0.25},
        "mood": "delicate, storybook, quiet, constructed",
        "leads": ["Layered cut-paper diorama in a shadow box, {cap}:",
                  "Hand-cut paper theatre with stacked planes, {cap}:",
                  "Papercut scene built in receding layers, {cap}:"],
        "substrates": ["textured coloured cardstock", "heavy watercolour paper",
                       "thin tracing paper and cardstock mixed", "corrugated board and tissue"],
        "core": "the scene built from separate stacked planes of cut paper with real air between them",
        "palettes": ["a narrow range of blues and greys deepening with distance",
                     "warm creams and ochres", "high-contrast black and white with one red",
                     "soft faded pastels"],
        "emphasis": ["the cut edge of every layer catching the light",
                     "drop shadows falling from each plane onto the next",
                     "the paper's tooth visible across the flat areas",
                     "translucent tissue glowing where light passes through"],
        "artifacts": ["a slightly ragged cut where the blade slipped",
                      "visible glue tabs holding a layer",
                      "one layer buckling away from flat",
                      "a pencil guideline left uncut",
                      "dust settled in the gaps between layers"],
        "captures": ["lit from one side to throw the layer shadows long",
                     "backlit so the tissue layers glow",
                     "photographed straight on in flat museum light"],
        "wear": ["crisply new", "sun-faded on one side", "dented from storage"],
    },
    "stainedglass": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.75, "energy": 0.6, "warmth": 0.55, "age": 0.85, "tactility": 0.7, "scale": 0.55, "organic": 0.2},
        "mood": "transcendent, devotional, radiant",
        "leads": ["Stained glass panel, {cap}:",
                  "Leaded glass window, {cap}:",
                  "Painted and fired glass panel in lead came, {cap}:"],
        "substrates": ["hand-blown cathedral glass", "opalescent glass",
                       "streaky antique glass", "thick slab glass set in concrete"],
        "core": "saturated coloured glass divided by heavy dark lead lines, lit from behind",
        "palettes": ["deep cobalt and ruby with gold", "cool greens and blue-greys",
                     "amber and bottle green", "predominantly white and silver-stain yellow"],
        "emphasis": ["bubbles and striations trapped in the hand-blown glass",
                     "the black lead came drawing every contour",
                     "painted grisaille shading fired onto the glass",
                     "colour spilling onto the surrounding stone"],
        "artifacts": ["a cracked pane held by a repair lead",
                      "one pane replaced in a mismatched colour",
                      "dirt and grime built up in the lower corners",
                      "the lead sagging and bowing with age",
                      "condensation blurring part of the panel"],
        "captures": ["backlit by grey daylight", "backlit by low warm sun, colour thrown across the frame",
                     "photographed at an angle so the glass surface reflects"],
        "wear": ["newly leaded and bright", "centuries old, buckled and grimy",
                 "partly restored, some panes clean and some dark"],
    },
    "verdigris": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.25, "energy": 0.55, "warmth": 0.35, "age": 0.9, "tactility": 0.9, "scale": 0.4, "organic": 0.15},
        "mood": "ancient, corroded, heavy, elemental",
        "leads": ["Oxidised copper relief panel, {cap}:",
                  "Hammered bronze plaque with patina, {cap}:",
                  "Repoussé copper sheet, corroded, {cap}:"],
        "substrates": ["hammered copper sheet", "cast bronze", "beaten brass plate"],
        "core": "raised metal forms worked in relief, the surface eaten by patina",
        "palettes": ["deep verdigris green over raw copper",
                     "blue-green patina with black recesses",
                     "brown-black bronze with green only in the hollows",
                     "bright polished metal against corroded areas"],
        "emphasis": ["hammer facets across the flat areas",
                     "mineral crust built up thick in the recesses",
                     "corrosion pitting eating into the raised forms",
                     "polished high points where hands have rubbed it"],
        "artifacts": ["a repair patch soldered across one area",
                      "drips of green running down from the recesses",
                      "a dent distorting the relief",
                      "rivet heads punching through the design",
                      "salt bloom crusting one edge"],
        "captures": ["in hard raking light so the relief throws shadows",
                     "under flat overcast light", "lit from below, shadows running upward"],
        "wear": ["freshly patinated", "centuries buried and only just cleaned",
                 "weathered outdoors for decades"],
    },
    "ukiyoe": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.6, "energy": 0.45, "warmth": 0.55, "age": 0.8, "tactility": 0.35, "scale": 0.5, "organic": 0.3},
        "mood": "stylized, flowing, poised",
        "leads": ["Japanese woodblock ukiyo-e print on {sub}:",
                  "Multi-block nishiki-e colour woodcut on {sub}:",
                  "Hand-printed woodblock impression on {sub}:"],
        "substrates": ["aged mulberry washi paper", "thin kozo paper",
                       "cream hosho paper"],
        "core": "flat carved colour planes bounded by a printed keyline, no shading",
        "palettes": ["indigo and safflower red with black keyline",
                     "muted mineral greens and ochres",
                     "predominantly indigo blues (aizuri-e)",
                     "faded pinks and greys, the fugitive pigments gone"],
        "emphasis": ["woodgrain printing through the flat colour areas",
                     "the bokashi gradient hand-wiped on the block",
                     "the embossed impression of the block in the paper",
                     "the crisp carved keyline"],
        "artifacts": ["one colour block slightly out of register",
                      "a wormhole through the sheet",
                      "the paper browned and brittle at the edges",
                      "an ink-heavy pull with the colour gone muddy",
                      "a horizontal fold from being bound in an album"],
        "captures": ["photographed flat in even light", "scanned flat",
                     "lit at a low angle so the paper texture and embossing read"],
        "wear": ["a fresh early impression", "faded by two centuries of light",
                 "water-stained along one edge"],
    },
    "raku": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.45, "energy": 0.7, "warmth": 0.7, "age": 0.6, "tactility": 0.9, "scale": 0.25, "organic": 0.2},
        "mood": "volatile, lustrous, earthy",
        "leads": ["Raku-fired ceramic surface, {cap}:",
                  "Glazed and reduction-fired stoneware, {cap}:",
                  "Pit-fired earthenware with lustre glaze, {cap}:"],
        "substrates": ["grogged stoneware clay", "smooth white earthenware",
                       "dark iron-rich clay body"],
        "core": "a thick glaze crazed into a fine crackle over a scorched clay body",
        "palettes": ["copper lustre iridescence over black",
                     "white crackle glaze with carbon-blackened crazing",
                     "turquoise glaze breaking to bronze at the edges",
                     "unglazed smoke-blackened clay with one glazed passage"],
        "emphasis": ["the crackle network filled with carbon",
                     "glaze pooling thick in the hollows and thin on the ridges",
                     "flashing where the flame licked the piece",
                     "raw grogged clay contrasting with glassy glaze"],
        "artifacts": ["a firing crack running through the piece",
                      "a bare patch where the glaze crawled",
                      "kiln shelf scars on the underside",
                      "pinholes bubbled through the glaze",
                      "an ash deposit fused to one side"],
        "captures": ["lit hard so the lustre flares", "in soft light showing the crackle",
                     "macro close on the glaze surface"],
        "wear": ["straight from the reduction bin", "handled for years, lustre worn thin",
                 "chipped at the rim"],
    },
}

# Cross-family palette-ish global look, sampled per video so different videos
# of the same family still differ.
GLOBAL_GRADE = [
    "the whole image slightly cool", "the whole image slightly warm",
    "low contrast and dusty", "high contrast and clean",
    "a touch overexposed", "a touch dark and dense",
]

BY_LEVEL = {
    "low": ["cyanotype", "collodion", "etching", "cutpaper", "ukiyoe"],
    "mid": ["etching", "ukiyoe", "verdigris", "cutpaper", "raku"],
    "high": ["felted", "risograph", "stainedglass", "raku", "verdigris"],
}

MATERIALS = FAMILIES  # back-compat for specs that reference family keys


def compose(family_key: str, seed: int, n_artifacts: int = 2) -> dict:
    """Sample one concrete treatment from a family.

    Same key + same seed always yields the same treatment, so a manifest
    reproduces. Different seeds yield materially different objects rather
    than the same string every time.
    """
    fam = FAMILIES[family_key]
    rng = random.Random(seed)

    sub = rng.choice(fam["substrates"])
    cap = rng.choice(fam["captures"])
    pal = rng.choice(fam["palettes"])
    lead = rng.choice(fam["leads"]).format(sub=sub, cap=cap, pal=pal)

    picks = rng.sample(fam["artifacts"], min(n_artifacts, len(fam["artifacts"])))
    style = ". ".join([
        fam["core"].capitalize(),
        f"Colour: {pal}",
        f"Surface: {rng.choice(fam['emphasis'])}",
        f"Condition: {rng.choice(fam['wear'])}",
        f"Flaws: {'; '.join(picks)}",
        rng.choice(GLOBAL_GRADE).capitalize(),
        "No photorealism — the material and the process that made it are the subject",
    ]) + "."
    return {"lead": lead, "style": style, "family": family_key,
            "substrate": sub, "palette": pal, "artifacts": picks}


def jitter(family_key: str, base_seed: int, shot_seed: int) -> dict:
    """Per-shot variation: same object family and palette, fresh flaws.

    Keeps a scene coherent while making each shot read as its own physical
    artefact — a different sheet, a different pull — instead of one image
    with a filter over it.
    """
    base = compose(family_key, base_seed)
    rng = random.Random(shot_seed)
    fam = FAMILIES[family_key]
    picks = rng.sample(fam["artifacts"], min(2, len(fam["artifacts"])))
    style = base["style"].replace(
        f"Flaws: {'; '.join(base['artifacts'])}", f"Flaws: {'; '.join(picks)}")
    return {"lead": base["lead"], "style": style, "family": family_key}


# Second tranche — widens the grammar so vibe matching has real range to
# choose from rather than ten options. Same structure; affinity axes are
# valence (bleak..joyful), energy (still..frantic), warmth (cold..warm),
# age (contemporary..antique), tactility (flat..dimensional).
FAMILIES.update({
    "lithograph": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.4, "energy": 0.35, "warmth": 0.4, "age": 0.8, "tactility": 0.3, "scale": 0.35, "organic": 0.2},
        "mood": "smoky, tonal, brooding, literary",
        "leads": ["Stone lithograph printed on {sub}:", "Hand-drawn litho crayon print on {sub}:",
                  "Tusche-wash lithograph on {sub}:"],
        "substrates": ["heavy cream printmaking paper", "soft grey wove paper",
                       "thin cover stock", "buff-toned rag paper"],
        "core": "continuous greasy tone drawn with litho crayon, grain of the stone carried into every mark",
        "palettes": ["dense black on cream", "warm bistre brown", "two stones, black over pale ochre",
                     "cold grey-black with a blue undertone"],
        "emphasis": ["the granular tooth of the stone in every mid-tone",
                     "wash passages pooling into mottled tone",
                     "crayon strokes still legible in the darks",
                     "bright untouched paper carrying the highlights"],
        "artifacts": ["scumming greying the open areas", "a roller mark across the sheet",
                      "the stone's edge printing faintly", "one passage filled in too dark",
                      "a thumbprint in the margin"],
        "captures": ["photographed flat under soft light", "scanned flat",
                     "raking light showing the paper tooth"],
        "wear": ["a crisp early pull", "yellowed and foxed", "rubbed and smudged at the edges"],
    },
    "silkscreen": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.75, "energy": 0.75, "warmth": 0.5, "age": 0.3, "tactility": 0.4, "scale": 0.3, "organic": 0.1},
        "mood": "bold, flat, pop, insistent",
        "leads": ["Hand-pulled silkscreen print on {sub}:", "Serigraph, {pal}, on {sub}:",
                  "Screen print with heavy ink deposit on {sub}:"],
        "substrates": ["heavy poster stock", "coarse chipboard", "bright white card",
                       "brown kraft paper"],
        "core": "flat opaque ink laid in separate screens, hard-edged shapes with no gradation",
        "palettes": ["three flat colours plus black", "day-glo orange and deep blue",
                     "monochrome black on coloured stock", "muted olive, rust and bone"],
        "emphasis": ["the thick raised ink you can feel", "the weave of the mesh in the flat areas",
                     "hard knife-cut stencil edges", "one screen slightly translucent over another"],
        "artifacts": ["a pinhole letting ink through where it shouldn't",
                      "the squeegee starting mark at one edge", "registration off by a hair",
                      "ink drying patchy in a large flat", "fibres stuck in the wet ink"],
        "captures": ["photographed flat, hard even light", "at an angle so the ink relief catches light",
                     "taped to a studio wall"],
        "wear": ["fresh and glossy", "sun-bleached in the fluorescents", "creased and thumbed"],
    },
    "embroidery": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.7, "energy": 0.3, "warmth": 0.85, "age": 0.6, "tactility": 0.9, "scale": 0.2, "organic": 0.35},
        "mood": "patient, domestic, intimate, devotional",
        "leads": ["Hand-embroidered panel on {sub}:", "Silk thread embroidery worked on {sub}:",
                  "Crewelwork in wool on {sub}:"],
        "substrates": ["coarse natural linen", "even-weave cotton", "loosely woven hessian",
                       "fine bleached lawn"],
        "core": "the image worked entirely in stitches, thread direction shaping every form",
        "palettes": ["muted vegetable-dyed wools", "bright silks against undyed ground",
                     "a single dark thread on pale cloth", "faded pinks, sage and bone"],
        "emphasis": ["the sheen of silk floss catching light along the stitch direction",
                     "the woven grid of the ground cloth showing between stitches",
                     "raised satin stitch standing proud of the surface",
                     "long-and-short shading blending one colour into the next"],
        "artifacts": ["loose thread ends left hanging on the reverse showing through",
                      "the hoop's ring pressed into the cloth", "one area unfinished, ground cloth bare",
                      "a knot pulling the weave tight", "colours faded unevenly by light"],
        "captures": ["raking light so the stitches throw shadows", "macro close on the thread",
                     "flat-lit and pinned taut"],
        "wear": ["newly finished, thread still bright", "an heirloom, faded and softened",
                 "moth-nibbled at one corner"],
    },
    "fresco": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.5, "energy": 0.3, "warmth": 0.7, "age": 0.95, "tactility": 0.75, "scale": 0.6, "organic": 0.2},
        "mood": "monumental, sun-bleached, ruined, sacred",
        "leads": ["Buon fresco on {sub}:", "Wall painting in lime plaster on {sub}:",
                  "Fragment of a fresco cycle on {sub}:"],
        "substrates": ["lime plaster over rough masonry", "thin intonaco over brick",
                       "plaster laid on a curved vault"],
        "core": "pigment sunk into damp lime plaster, matte and chalky, part of the wall itself",
        "palettes": ["earth reds, ochres and lime white", "faded azurite blue and terre verte",
                     "sun-bleached to pale pinks and buffs", "charcoal underdrawing showing through"],
        "emphasis": ["giornata joins where a day's plaster meets the next",
                     "the chalky matte surface refusing to shine",
                     "incised guidelines cut into the wet plaster",
                     "the rough aggregate of the plaster showing through thin passages"],
        "artifacts": ["large losses where the plaster has fallen away",
                      "a crack running through the composition", "salt efflorescence blooming white",
                      "smoke blackening across one corner", "later graffiti scratched into the surface"],
        "captures": ["lit by raking daylight from a high window", "flat archaeological documentation lighting",
                     "photographed at an angle showing the wall's curve"],
        "wear": ["recently uncovered and cleaned", "centuries of soot and loss",
                 "partly restored, losses filled flat"],
    },
    "linocut": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.55, "energy": 0.65, "warmth": 0.45, "age": 0.5, "tactility": 0.45, "scale": 0.35, "organic": 0.2},
        "mood": "blunt, vigorous, graphic, worked",
        "leads": ["Linocut relief print on {sub}:", "Hand-burnished lino block print on {sub}:",
                  "Reduction linocut on {sub}:"],
        "substrates": ["thin Japanese printing paper", "heavy cartridge paper",
                       "newsprint", "tinted sugar paper"],
        "core": "bold cut shapes with visible gouge marks, ink sitting flat on the raised surface",
        "palettes": ["black ink only", "black over one flat colour",
                     "three reduction layers, dark to light", "red and black on cream"],
        "emphasis": ["the chatter of the gouge across cleared areas",
                     "chunky uncut blacks against fine cut lines",
                     "ink slightly heavier at the block edges",
                     "the paper's texture breaking the flat ink"],
        "artifacts": ["clearing marks printing as faint grey texture",
                      "the block edge printing as a hard border", "an under-inked patch going pale",
                      "a slip of the gouge cutting into a form", "burnishing marks on the reverse showing"],
        "captures": ["photographed flat", "held up, paper slightly rippled", "scanned flat"],
        "wear": ["a clean fresh pull", "a late pull, block worn", "creased from storage"],
    },
    "daguerreotype": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.2, "energy": 0.15, "warmth": 0.25, "age": 1.0, "tactility": 0.5, "scale": 0.25, "organic": 0.15},
        "mood": "spectral, mirror-like, uncanny, funereal",
        "leads": ["Daguerreotype on {sub}:", "Mirror-polished daguerreotype plate, {cap}:",
                  "Sixth-plate daguerreotype, {cap}:"],
        "substrates": ["silver-plated copper", "highly polished silvered plate"],
        "core": "a mirror surface holding a faint image that flips positive to negative as the angle shifts",
        "palettes": ["silver-white and shadow with no true black", "warm gilt-toned silver",
                     "cold steel grey", "hand-tinted pink on the cheeks only"],
        "emphasis": ["the mirror ground reflecting whatever is in front of it",
                     "buffing scratches circling the plate",
                     "impossibly fine detail in the highlights",
                     "the image dissolving to nothing at certain angles"],
        "artifacts": ["tarnish blooming in rainbow rings from the edges",
                      "the brass mat's impression around the image", "a wipe mark across the plate",
                      "dust motes fused to the silver", "black spotting eating into the image"],
        "captures": ["photographed against black so the image reads positive",
                     "tilted so half the plate flares to mirror", "under glass in its case"],
        "wear": ["freshly sealed and brilliant", "heavily tarnished", "cracked cover glass over it"],
    },
    "mosaic": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.65, "energy": 0.5, "warmth": 0.6, "age": 0.9, "tactility": 0.85, "scale": 0.55, "organic": 0.15},
        "mood": "eternal, fragmented, ceremonial, patient",
        "leads": ["Tessellated mosaic in {sub}:", "Byzantine-style mosaic worked in {sub}:",
                  "Floor mosaic laid in {sub}:"],
        "substrates": ["gold-leaf glass smalti", "cut stone and marble tesserae",
                       "terracotta and limestone cubes", "mixed glass and shell"],
        "core": "the image assembled from thousands of small hard tesserae with visible mortar between them",
        "palettes": ["gold ground with deep blues and reds", "muted stone naturals",
                     "black and white geometric only", "sea greens and bone"],
        "emphasis": ["each tessera set at a slightly different angle, catching light unevenly",
                     "the andamento, rows of tesserae flowing around the forms",
                     "grout lines drawing a grid across everything",
                     "gold tesserae flaring where the light hits"],
        "artifacts": ["a section lost, bare mortar bed showing", "later repairs in mismatched stone",
                      "the floor buckled by subsidence", "lime crust over one area",
                      "a crack running through, tesserae displaced"],
        "captures": ["lit obliquely so every tessera casts a shadow",
                     "photographed from directly above", "under a shaft of daylight"],
        "wear": ["newly laid and sharp", "worn smooth by centuries of feet", "excavated and partly cleaned"],
    },
    "chemigram": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.35, "energy": 0.85, "warmth": 0.4, "age": 0.4, "tactility": 0.6, "scale": 0.4, "organic": 0.25},
        "mood": "chaotic, alchemical, corroded, feverish",
        "leads": ["Chemigram on {sub}:", "Darkroom chemigram, developer and fixer painted onto {sub}:",
                  "Cameraless chemical painting on {sub}:"],
        "substrates": ["fibre-based silver gelatin paper", "expired resin-coated paper",
                       "large-format sheet film"],
        "core": "form emerging from chemistry eating into the emulsion, not from a lens",
        "palettes": ["silver-black bleeding into cream", "sepia and bruised violet",
                     "cold blue-black with bleached voids", "toned brown with metallic sheen"],
        "emphasis": ["tide lines where the chemistry crept",
                     "solarised edges reversing tone", "crystalline blooms in the emulsion",
                     "the resist's mark where it held the developer off"],
        "artifacts": ["drips running against the composition", "the emulsion lifting and wrinkling",
                      "fingerprints developed into the image", "a bleached hole burnt through",
                      "spatter across one corner"],
        "captures": ["scanned flat", "photographed wet and glistening", "pinned up, curling"],
        "wear": ["still wet from the tray", "dried and cockled", "silvered out with age"],
    },
    "batik": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.7, "energy": 0.45, "warmth": 0.8, "age": 0.65, "tactility": 0.7, "scale": 0.3, "organic": 0.35},
        "mood": "sinuous, ceremonial, saturated, flowing",
        "leads": ["Wax-resist batik on {sub}:", "Hand-drawn tulis batik on {sub}:",
                  "Multiple-dip batik dyed on {sub}:"],
        "substrates": ["fine cotton cloth", "heavy silk", "coarse handwoven cotton"],
        "core": "colour laid by repeated dyeing, wax holding back each area, cloth weave throughout",
        "palettes": ["indigo and soga brown on cream", "deep rust, indigo and black",
                     "single indigo dip, pale to saturated", "turmeric yellow and madder red"],
        "emphasis": ["the crackle where wax broke and dye seeped into the veins",
                     "the canting's hand-drawn line wavering slightly",
                     "the cloth's weave visible through the dye",
                     "colour bleeding softly at every boundary"],
        "artifacts": ["wax residue leaving a stiff patch", "a dye run down one edge",
                      "uneven dyeing leaving cloudy bands", "a repair stitched across a tear",
                      "the selvedge fraying"],
        "captures": ["hung so the cloth falls in soft folds", "pinned flat, backlit faintly",
                     "photographed flat in even daylight"],
        "wear": ["newly dyed and vivid", "washed many times and softened",
                 "sun-faded along one fold"],
    },
    "charcoal": {
        "suits": "any location; the material is a picture of the place, so scale is free",
        "kind": "craft",
        "affinity": {"valence": 0.3, "energy": 0.55, "warmth": 0.45, "age": 0.55, "tactility": 0.5, "scale": 0.35, "organic": 0.25},
        "mood": "urgent, smudged, unresolved, breathing",
        "leads": ["Charcoal and white chalk drawing on {sub}:", "Vine charcoal study on {sub}:",
                  "Compressed charcoal drawing, heavily reworked, on {sub}:"],
        "substrates": ["grey-toned laid paper", "buff sugar paper", "rough grey card",
                       "warm-toned pastel paper"],
        "core": "the image built in smudged charcoal with the toned paper carrying the mid-tone",
        "palettes": ["charcoal black and white chalk on grey",
                     "black only, paper doing the rest", "black and sanguine on buff",
                     "soft greys with one dense black accent"],
        "emphasis": ["fingerprints where the charcoal was blended by hand",
                     "the paper's tooth grabbing the charcoal",
                     "erased passages ghosting under the surface",
                     "white chalk sitting chalky and opaque on top"],
        "artifacts": ["smudges dragged outside the forms", "a pentimento of an earlier position showing",
                      "fixative spray mottling one area", "the sheet's fold running through",
                      "loose charcoal dust caught in the tooth"],
        "captures": ["raking light showing the paper tooth", "photographed flat and even",
                     "pinned to a board, corners curling"],
        "wear": ["fresh and unfixed, still dusty", "rubbed and blurred from handling",
                 "yellowed, the chalk gone dull"],
    },
})

BY_LEVEL = {
    "low": ["cyanotype", "collodion", "etching", "cutpaper", "ukiyoe",
            "lithograph", "daguerreotype", "charcoal"],
    "mid": ["etching", "ukiyoe", "verdigris", "cutpaper", "raku",
            "lithograph", "embroidery", "linocut", "mosaic", "batik", "fresco"],
    "high": ["felted", "risograph", "stainedglass", "raku", "verdigris",
             "silkscreen", "chemigram", "linocut"],
}


# Third tranche — not craft techniques but matter and scale. A craft family
# says "printed on paper"; these say the scene is *constituted* from a
# substance, or *observed through* an instrument. Same machinery, different
# lead and core phrasing. Two extra axes carry them: scale (intimate..vast)
# and organic (inert/geometric..living).
FAMILIES.update({
    "mycology": {
        "suits": "damp, rotting, enclosed or forest places — cellars, fallen timber, wet undergrowth, decaying interiors",
        "kind": "substance",
        "affinity": {"valence": 0.4, "energy": 0.3, "warmth": 0.6, "age": 0.5,
                     "tactility": 0.95, "scale": 0.25, "organic": 1.0},
        "mood": "damp, proliferating, patient, decomposing",
        "leads": ["The entire scene grown from {sub}:",
                  "Everything in frame formed of {sub}, photographed {cap}:",
                  "A living fungal sculpture of the scene in {sub}, {cap}:"],
        "substrates": ["dense white mycelium", "bracket fungi shelving out in tiers",
                       "clustered oyster mushroom caps", "slime mould creeping in yellow veins",
                       "fine cobweb mould over damp wood"],
        "core": "every form built from fungal growth, soft-edged and swelling, colonising the shapes rather than depicting them",
        "palettes": ["bone white and bruise grey", "amber, rust and liver brown",
                     "pale flesh pinks with black gills", "sulphur yellow against wet black wood"],
        "emphasis": ["the velvety bloom of fresh mycelium",
                     "gills radiating in fine parallel blades",
                     "spore dust settled on the surfaces below",
                     "translucent flesh where the light passes through a cap"],
        "artifacts": ["a slug track cut through the growth", "one lobe collapsed and liquefying",
                      "condensation beaded on every surface", "insect boreholes riddling a stem",
                      "the substrate rotting through underneath"],
        "captures": ["in damp diffuse forest light", "macro with a ring light, background black",
                     "lit from behind so the caps glow translucent",
                     "top-down on the forest floor"],
        "wear": ["freshly flushed and turgid", "past its peak, deliquescing at the edges",
                 "dried to leather and papery"],
    },
    "botanical": {
        "suits": "gardens, meadows, herbaria, pressed and catalogued places; anything that was once growing",
        "kind": "substance",
        "affinity": {"valence": 0.65, "energy": 0.2, "warmth": 0.7, "age": 0.6,
                     "tactility": 0.8, "scale": 0.3, "organic": 0.95},
        "mood": "pressed, elegiac, catalogued, fragile",
        "leads": ["Herbarium specimen: the scene composed entirely of {sub}, {cap}:",
                  "The whole scene assembled from {sub} and pressed flat, {cap}:",
                  "Botanical arrangement of {sub} forming the scene, {cap}:"],
        "substrates": ["pressed skeletal leaves", "dried fern fronds and seed heads",
                       "flattened flower petals and stems", "moss and lichen mats",
                       "translucent honesty seed pods"],
        "core": "the scene made from flattened plant matter, every form a real leaf or stem laid in place",
        "palettes": ["faded sage, straw and rust", "chlorophyll green bleached to yellow",
                     "sepia browns of long-dried specimens", "silver-grey lichen against black"],
        "emphasis": ["the vein network showing through each translucent leaf",
                     "the brittle curl at every dried edge",
                     "overlapping layers casting soft shadows",
                     "fine root hairs fanning out like drawn lines"],
        "artifacts": ["a leaf cracked across from handling", "old adhesive strips holding a stem down",
                      "insect damage lacing one leaf", "foxing spots on the mounting sheet",
                      "a faded handwritten label edge intruding"],
        "captures": ["flat on a mounting sheet under museum light",
                     "backlit so the leaf veins glow", "scanned flat and sharp",
                     "raking light throwing the curled edges into relief"],
        "wear": ["freshly pressed and still supple", "a century in the cabinet, brittle and faded",
                 "water-stained and partly lost"],
    },
    "entomological": {
        "suits": "hives, undergrowth, specimen drawers, swarming or chitinous places; close, teeming interiors",
        "kind": "substance",
        "affinity": {"valence": 0.35, "energy": 0.5, "warmth": 0.45, "age": 0.55,
                     "tactility": 0.9, "scale": 0.15, "organic": 0.9},
        "mood": "iridescent, uneasy, jewelled, precise",
        "leads": ["The scene constructed entirely from {sub}, {cap}:",
                  "Every surface formed of {sub}, {cap}:",
                  "An entomological assemblage of {sub} composing the scene, {cap}:"],
        "substrates": ["beetle elytra in overlapping iridescent plates",
                       "moth wings with their scale dust intact",
                       "dragonfly wing membrane veined like leaded glass",
                       "chitin carapace segments and jointed legs",
                       "cicada husks, hollow and translucent"],
        "core": "the forms built from insect anatomy — chitin, wing membrane and scale — jointed and segmented rather than modelled",
        "palettes": ["oil-slick green and violet iridescence over black",
                     "powdery moth greys and fawns", "amber translucence with dark veining",
                     "metallic blue-green with copper edges"],
        "emphasis": ["structural colour shifting with the viewing angle",
                     "the fine scale dust on a wing catching light",
                     "the veined lattice of a transparent wing",
                     "hair-fine setae bristling along every edge"],
        "artifacts": ["a wing torn and missing a section", "a pin hole through a thorax",
                      "scale dust rubbed away in one patch", "a leg detached and set beside the body",
                      "dust settled in the joints"],
        "captures": ["macro with focus stacking, black background",
                     "under a raking light so the iridescence flares",
                     "pinned in a specimen drawer under glass",
                     "backlit so the membranes glow"],
        "wear": ["freshly set and brilliant", "faded in the drawer for decades",
                 "brittle and partly crumbled"],
    },
    "microbial": {
        "suits": "laboratories, petri dishes, sealed vessels, wet surfaces; small enclosed spaces seen very close",
        "kind": "substance",
        "affinity": {"valence": 0.4, "energy": 0.45, "warmth": 0.5, "age": 0.3,
                     "tactility": 0.7, "scale": 0.1, "organic": 0.95},
        "mood": "proliferating, clinical, alive, faintly wrong",
        "leads": ["Bacterial culture grown into the scene on {sub}, {cap}:",
                  "The image rendered as colony growth across {sub}, {cap}:",
                  "Agar art: the scene cultured in living colonies on {sub}, {cap}:"],
        "substrates": ["nutrient agar in a glass petri dish", "blood agar gone dark red",
                       "a large square culture plate", "agar poured over a photographic mask"],
        "core": "the forms drawn by living colonies spreading across a culture plate, edges lobed and creeping",
        "palettes": ["cream and ochre colonies on amber agar",
                     "vivid pigmented strains — violet, gold and coral",
                     "translucent films barely visible against the medium",
                     "black mould creeping into pale bacterial lawns"],
        "emphasis": ["the lobed irregular margin of each spreading colony",
                     "concentric growth rings where the colony pulsed outward",
                     "clear zones where one strain inhibits another",
                     "condensation on the lid blurring part of the view"],
        "artifacts": ["a contaminating mould colony taking over one corner",
                      "the inoculation loop's streak lines still visible",
                      "the agar cracked and pulling from the dish wall",
                      "a bubble trapped in the medium",
                      "handwriting on the dish base showing through"],
        "captures": ["lit from below on a light box", "photographed straight down through the lid",
                     "dark-field lighting against black", "in flat clinical lab light"],
        "wear": ["24 hours' growth, edges still sharp", "overgrown, colonies merged into a mat",
                 "dried out and cracked"],
    },
    "mineral": {
        "suits": "caves, geodes, mines, cracked ground; places of rock and crystal growth",
        "kind": "substance",
        "affinity": {"valence": 0.6, "energy": 0.35, "warmth": 0.4, "age": 0.7,
                     "tactility": 0.85, "scale": 0.35, "organic": 0.1},
        "mood": "glittering, geological, hard, treasured",
        "leads": ["The scene crystallised in {sub}, {cap}:",
                  "Every form grown as {sub}, {cap}:",
                  "A geode cross-section in which the scene appears as {sub}, {cap}:"],
        "substrates": ["druzy quartz crystal", "banded agate and chalcedony",
                       "faceted gemstone in many colours", "amethyst points lining a cavity",
                       "pyrite cubes and native copper"],
        "core": "the forms built from crystal growth — faceted, banded and refractive, hard-edged where the lattice dictates",
        "palettes": ["amethyst violet with milky quartz", "banded agate reds, whites and greys",
                     "cold colourless quartz with rainbow internal fractures",
                     "gold pyrite against black matrix"],
        "emphasis": ["light refracting and doubling inside the crystal",
                     "the sugar-glitter of a druzy surface",
                     "concentric banding recording each growth phase",
                     "internal fractures scattering rainbows"],
        "artifacts": ["a cleaved face shearing off one form",
                      "iron staining bleeding through the bands",
                      "a hollow vug where growth stopped",
                      "the rough host rock still clinging to one edge",
                      "a saw mark across the cut face"],
        "captures": ["lit hard so the facets throw spectra", "backlit to show internal banding",
                     "macro on the crystal faces", "wet, on black slate"],
        "wear": ["freshly cut and polished", "dusty from the collection drawer",
                 "weathered where it lay exposed"],
    },
    "lithic": {
        "suits": "cliffs, quarries, monuments, ruins, carved facades; large weathered stone places",
        "kind": "substance",
        "affinity": {"valence": 0.35, "energy": 0.3, "warmth": 0.4, "age": 0.95,
                     "tactility": 0.9, "scale": 0.7, "organic": 0.1},
        "mood": "monumental, eroded, mute, enduring",
        "leads": ["Carved in {sub}, {cap}:", "The scene cut as a relief into {sub}, {cap}:",
                  "Weathered {sub} carving of the scene, {cap}:"],
        "substrates": ["coarse yellow sandstone", "hard grey basalt", "weathered limestone",
                       "white marble with grey veining", "granite flecked with mica"],
        "core": "the scene cut into rock as relief, the stone's own grain and weathering as present as the carving",
        "palettes": ["warm sandstone golds and rust streaks", "cold grey basalt with black shadow",
                     "bleached limestone white against deep shade",
                     "marble white with grey veins running through the forms"],
        "emphasis": ["chisel marks still legible across the flat ground",
                     "the stone's bedding planes cutting across the carved forms",
                     "edges softened and rounded by centuries of rain",
                     "lichen colonising the sheltered hollows"],
        "artifacts": ["a large spall lost from one area", "iron staining bleeding from a cramp",
                      "a crack running through the relief", "salt crystallising in the pores",
                      "later graffiti cut across an older surface"],
        "captures": ["in hard low sun so the relief throws long shadows",
                     "under flat overcast light", "wet with rain, contrast raised",
                     "lit from one side at night"],
        "wear": ["newly cut, edges crisp", "millennia of weathering, forms half-read",
                 "buried and recently excavated"],
    },
    "ferrofluid": {
        "suits": "labs, dark reflective voids, pooling liquid surfaces; abstract or near-abstract spaces",
        "kind": "substance",
        "affinity": {"valence": 0.45, "energy": 0.75, "warmth": 0.3, "age": 0.1,
                     "tactility": 0.8, "scale": 0.2, "organic": 0.15},
        "mood": "sleek, alien, kinetic, unsettling",
        "leads": ["The scene formed in {sub}, {cap}:",
                  "Everything rendered as {sub} under magnetic influence, {cap}:",
                  "Non-Newtonian {sub} pulled into the shape of the scene, {cap}:"],
        "substrates": ["black ferrofluid spiking along field lines",
                       "cornstarch suspension tearing and healing",
                       "mercury beading into fat lenses",
                       "thick oobleck standing in frozen peaks",
                       "magnetorheological fluid gone momentarily solid"],
        "core": "the forms held in a fluid that behaves like a solid — spiked, beading, tearing and reflowing rather than sculpted",
        "palettes": ["liquid black with hard specular highlights",
                     "mercury silver reflecting the whole room",
                     "milk white with a matte non-Newtonian skin",
                     "black fluid over a coloured underlit base"],
        "emphasis": ["the regular spike lattice pulled up by the field",
                     "perfect mirror reflections curving over every bulge",
                     "the moment of tearing where the fluid splits",
                     "the surface skinning over and then collapsing"],
        "artifacts": ["a stray droplet flung clear of the mass",
                      "the fluid slumping as the field weakens",
                      "an air bubble surfacing and bursting",
                      "residue trails left on the base plate",
                      "dust motes stuck in the surface tension"],
        "captures": ["hard specular lighting against black",
                     "underlit through a glass base", "high-speed flash freezing the motion",
                     "macro on the spike field"],
        "wear": ["at the instant of peak field", "collapsing back into a pool",
                 "settled and dulled with a skin"],
    },
    "cryo": {
        "suits": "frozen lakes, glaciers, frosted windows, winter fields; anything cold and still",
        "kind": "substance",
        "affinity": {"valence": 0.4, "energy": 0.35, "warmth": 0.05, "age": 0.4,
                     "tactility": 0.75, "scale": 0.4, "organic": 0.25},
        "mood": "brittle, silent, crystalline, suspended",
        "leads": ["The scene formed entirely in {sub}, {cap}:",
                  "Everything grown as {sub}, {cap}:",
                  "Frozen into {sub}, {cap}:"],
        "substrates": ["feathered hoarfrost", "clear lake ice with trapped bubbles",
                       "rime ice built into the wind", "frozen breath crystallising",
                       "cracked and refrozen ice layers"],
        "core": "the forms grown as ice crystal — feathered, faceted, and full of trapped air",
        "palettes": ["white on near-black water", "pale blue ice with white fracture planes",
                     "colourless crystal catching a low warm sun",
                     "grey-white rime against a flat white sky"],
        "emphasis": ["dendritic feathering repeating at every scale",
                     "chains of trapped bubbles frozen mid-rise",
                     "fracture planes catching light like flaws in glass",
                     "the surface subliming to a matte bloom"],
        "artifacts": ["a crack propagating through the ice with a white feather",
                      "debris frozen into the surface", "a partly thawed area gone slushy",
                      "wind-scoured grooves across the crust",
                      "refrozen meltwater glazing one region"],
        "captures": ["in cold blue dawn light", "backlit by low sun through the ice",
                     "macro on the frost feathers", "flat overcast, almost no shadow"],
        "wear": ["freshly formed overnight", "thawing and collapsing",
                 "old ice, milky and scarred"],
    },
    "sem": {
        "suits": "microscopic subjects only — pollen, fibres, dust, insect surfaces, fracture faces. NEVER a landscape or building",
        "kind": "instrument",
        "affinity": {"valence": 0.35, "energy": 0.5, "warmth": 0.15, "age": 0.2,
                     "tactility": 0.85, "scale": 0.05, "organic": 0.6},
        "mood": "alien, forensic, monumental at no scale, airless",
        "leads": ["Scanning electron micrograph of the scene, {cap}:",
                  "False-coloured SEM image in which the scene appears, {cap}:",
                  "Electron micrograph, the scene rendered as {sub}, {cap}:"],
        "substrates": ["gold-sputtered biological tissue", "a fracture surface of metal",
                       "pollen grains and spores", "a mineral dust aggregate",
                       "a synthetic fibre mat"],
        "core": "the image built from secondary-electron signal — no colour of its own, impossible depth of field, everything crisply lit from nowhere",
        "palettes": ["greyscale with no true black", "false-coloured in acid green and magenta",
                     "false-coloured in gold and deep blue", "warm sepia false colour"],
        "emphasis": ["surface texture resolved down to the sub-micron",
                     "charge build-up flaring one edge to white",
                     "everything in focus at once, front to back",
                     "shadowless illumination that seems to come from the lens"],
        "artifacts": ["a charging streak smearing across the frame",
                      "beam damage puckering one area", "a scale bar and data bar at the frame edge",
                      "contamination deposits speckling the surface",
                      "drift blurring one axis of the scan"],
        "captures": ["at 500x with a data bar", "at 20,000x, the subject unrecognisable",
                     "tilted stage, the specimen seen obliquely"],
        "wear": ["a clean freshly coated specimen", "beam-damaged from long exposure",
                 "poorly coated, charging badly"],
    },
    "cosmic": {
        "suits": "astronomical subjects only — nebulae, star fields, voids, planetary limbs. NEVER a terrestrial place",
        "kind": "instrument",
        "affinity": {"valence": 0.6, "energy": 0.55, "warmth": 0.3, "age": 0.5,
                     "tactility": 0.4, "scale": 1.0, "organic": 0.1},
        "mood": "vast, indifferent, luminous, ancient",
        "leads": ["Deep-space telescope composite in which the scene appears as {sub}, {cap}:",
                  "Narrowband astronomical image of the scene rendered as {sub}, {cap}:",
                  "Long-exposure astrophotograph, the scene formed of {sub}, {cap}:"],
        "substrates": ["emission nebula gas and dust", "a dense star field with diffraction spikes",
                       "dark dust lanes silhouetted against glowing hydrogen",
                       "a spiral galaxy's arms", "supernova remnant filaments"],
        "core": "the forms made of luminous gas, dust and stars at impossible scale, glowing from within rather than lit",
        "palettes": ["Hubble-palette gold, teal and deep red",
                     "hydrogen-alpha crimson against black",
                     "cold blue reflection nebula with white stars",
                     "monochrome with only the stars picked out"],
        "emphasis": ["dust lanes eating black holes out of the glow",
                     "diffraction spikes on every bright star",
                     "filament structure threading through the gas",
                     "the faint outer halo fading into noise"],
        "artifacts": ["a satellite trail crossing the frame",
                      "a cosmic ray hit as a bright pixel streak",
                      "stacking artefacts ghosting the bright stars",
                      "vignetting darkening the corners",
                      "one channel misregistered leaving colour fringes"],
        "captures": ["as a narrowband three-channel composite",
                     "as a long single exposure with visible noise",
                     "cropped tight so scale is unreadable"],
        "wear": ["a clean deep integration", "a short noisy exposure",
                 "an old plate scan with emulsion flaws"],
    },
    "crystallographic": {
        "suits": "atomic-scale subjects only — lattices, diffraction, grain boundaries. NEVER a place with a horizon",
        "kind": "instrument",
        "affinity": {"valence": 0.5, "energy": 0.6, "warmth": 0.2, "age": 0.25,
                     "tactility": 0.5, "scale": 0.05, "organic": 0.05},
        "mood": "rigorous, atomic, patterned, cold",
        "leads": ["Atomic-resolution image of the scene as {sub}, {cap}:",
                  "The scene resolved as {sub} in a lattice, {cap}:",
                  "Diffraction study in which the scene emerges from {sub}, {cap}:"],
        "substrates": ["a hexagonal atomic lattice", "an X-ray diffraction pattern of concentric spots",
                       "scanning tunnelling microscope topography",
                       "a quasicrystal tiling that never repeats",
                       "moiré fringes between two lattices"],
        "core": "the forms emerging from a regular atomic lattice — periodic, geometric, everything a consequence of the grid",
        "palettes": ["false-coloured orange-on-black height map",
                     "monochrome grey with white atomic sites",
                     "cold blue lattice with gold defect sites",
                     "black diffraction spots on white film"],
        "emphasis": ["individual atoms resolved as discrete bright points",
                     "the lattice's strict periodicity broken only at defects",
                     "moiré interference beating across the field",
                     "grain boundaries where two lattice orientations meet"],
        "artifacts": ["a dislocation line disrupting the rows",
                      "tip artefacts doubling every feature",
                      "thermal drift skewing the lattice",
                      "a vacancy where an atom is missing",
                      "scan noise streaking one direction"],
        "captures": ["as a false-coloured height map with a scale bar",
                     "as a raw greyscale scan", "as a reciprocal-space diffraction plate"],
        "wear": ["a clean atomically flat terrace", "a heavily defective sample",
                 "a drifting noisy acquisition"],
    },
    "radiographic": {
        "suits": "objects that can be seen through — bodies, luggage, machines, sealed containers. NEVER an open landscape",
        "kind": "instrument",
        "affinity": {"valence": 0.25, "energy": 0.3, "warmth": 0.1, "age": 0.4,
                     "tactility": 0.4, "scale": 0.2, "organic": 0.55},
        "mood": "ghostly, diagnostic, interior, unsentimental",
        "leads": ["Radiograph of the scene, {cap}:", "X-ray plate showing the scene as {sub}, {cap}:",
                  "The scene seen in transmission as {sub}, {cap}:"],
        "substrates": ["bone and soft tissue densities", "the internal structure of a machine",
                       "a pressed flower's skeleton", "layered strata of a sealed object"],
        "core": "the image formed by what absorbs the beam — density, not surface; interiors visible and surfaces gone",
        "palettes": ["greyscale negative, bone bright against black",
                     "inverted, dark structures on a light field",
                     "false-coloured in cold blue and bone white",
                     "sepia-toned old film emulsion"],
        "emphasis": ["dense structures glowing white and soft matter almost transparent",
                     "overlapping objects superimposing rather than occluding",
                     "the beam's fall-off darkening the frame edges",
                     "fine internal structure invisible from outside"],
        "artifacts": ["film grain across the plate", "a metal object flaring into pure white",
                      "motion blur through one region", "the cassette edge cutting the frame",
                      "chemical staining on the old film"],
        "captures": ["on a backlit viewing box", "as a digital plate, clean and flat",
                     "as aged film with emulsion damage"],
        "wear": ["a clean modern acquisition", "an old plate, fogged and stained",
                 "underexposed and grainy"],
    },
})

BY_LEVEL = {
    "low": ["cyanotype", "collodion", "etching", "cutpaper", "ukiyoe", "lithograph",
            "daguerreotype", "charcoal", "botanical", "cryo", "lithic", "radiographic"],
    "mid": ["etching", "ukiyoe", "verdigris", "cutpaper", "raku", "lithograph",
            "embroidery", "linocut", "mosaic", "batik", "fresco", "mycology",
            "mineral", "entomological", "cosmic"],
    "high": ["felted", "risograph", "stainedglass", "raku", "verdigris", "silkscreen",
             "chemigram", "linocut", "ferrofluid", "microbial", "crystallographic", "sem"],
}


# Families that work without a figure or a place — pure phenomena. Visualizer
# mode draws only from these, because an abstract cut sequence has no room to
# establish a character or a location and shouldn't try.
# Excludes families whose substrate implies a discrete object — raku means a
# pot, stained glass means a panel, mosaic means a floor — because in an
# abstract sequence the model photographs the object instead of filling the
# frame with the matter.
ABSTRACT = ["ferrofluid", "chemigram", "crystallographic", "mineral", "cryo",
            "sem", "cosmic", "microbial", "verdigris", "cyanotype"]
